accounts/urls.py
from django.conf.urls import url
from . import views

app_name = 'accounts'

urlpatterns = [
    url(r'^signup/$', views.signup_view, name="signup"),
    url(r'^login/$', views.login_view, name="login"),
    url(r'^logout/$', views.logout_view, name="logout"),
    url(r'^profile/$', views.profile_view, name="profile"),
]

articles/urls.py
from django.conf.urls import url
from . import views

app_name = 'articles'

urlpatterns = [
    url(r'^$', views.article_list, name="list"),
    url(r'^create/$', views.article_create, name="create"),
    url(r'^(?P<slug>[\w-]+)/$', views.article_detail, name="detail"),
    url(r'^delete/(?P<title>[\w-]+)/$', views.article_delete, name="delete"),
    url(r'^details/(?P<author>[\w-]+)/$', views.user_detail, name="details"),
]

djangonautic/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings
from articles import views as article_views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^articles/', include('articles.urls')),
    url(r'^accounts/', include('accounts.urls')),
    url(r'^about/$', views.about),
    url(r'^$', article_views.article_list, name="home"),
    url(r'^', include('favicon.urls')),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
#FAVICON_PATH = STATIC_URL + 'images/favicon.png'

accounts/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Profiles(models.Model):
    firstName = models.CharField(max_length=100)
    lastName = models.CharField(max_length=100)
    dob = models.DateTimeField()
    address = models.TextField()
    #username = models.ForeignKey(User, default=None, on_delete=models.CASCADE)
    date = models.DateTimeField(auto_now_add=True)
    #thumb = models.ImageField(default='default.png', blank=True)
    #author = models.ForeignKey(User, default=None, on_delete=models.CASCADE)

    def __str__(self):
        return self.firstName + self.lastName
    #def snippet(self):
        #return self.body[:50] + '...'

articles/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Article(models.Model):
    title = models.CharField(max_length=100)
    slug = models.SlugField()
    body = models.TextField()
    date = models.DateTimeField(auto_now_add=True)
    thumb = models.ImageField(default='default.png', blank=True)
    author = models.ForeignKey(User, default=None, on_delete=models.CASCADE)

    def __str__(self):
        return self.title

    def snippet(self):
        return self.body[:50] + '...'

accounts/forms.py
from django import forms
from . import models

class ProfileForm(forms.ModelForm):
    class Meta:
        model = models.Profiles
        fields = ['firstName', 'lastName', 'dob', 'address',]

articles/forms.py
from django import forms
from . import models

class CreateArticle(forms.ModelForm):
    class Meta:
        model = models.Article
        fields = ['title', 'body', 'slug', 'thumb',]

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, logout
from .models import Profiles
from . import forms

def signup_view(request):
    if request.method == 'POST':
         form = UserCreationForm(request.POST)
         details = forms.ProfileForm(request.POST)
         if form.is_valid() and details.is_valid():
             user = form.save()
             details.save()
             #  log the user in
             login(request, user)
             return redirect('articles:list')
    else:
        form = UserCreationForm()
        details = forms.ProfileForm()
    return render(request, 'accounts/signup.html', { 'form': form, 'details': details })

def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            # log the user in
            user = form.get_user()
            login(request, user)
            if 'next' in request.POST:
                return redirect(request.POST.get('next'))
            else:
               return redirect('articles:list')
    else:
        form = AuthenticationForm()
    return render(request, 'accounts/login.html', { 'form': form })

def logout_view(request):
    if request.method == 'POST':
            logout(request)
            return redirect('articles:list')

def profile_view(request):
    details = Profiles.objects.all()
    etails = Profiles.objects.get(username=request.user)
    return render(request, 'accounts/profile.html', { 'form': etails })

articles/views.py
#from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from .models import Article
from . import forms

def article_list(request):
    articles = Article.objects.all().order_by('date')
    return render(request, 'articles/article_list.html', {'articles': articles})

def article_detail(request, slug):
    # return HttpResponse(slug)
    article = Article.objects.get(slug=slug)
    return render(request, 'articles/article_detail.html', {'article': article})

@login_required(login_url="/accounts/login/")
def article_create(request):
    if request.method == 'POST':
        form = forms.CreateArticle(request.POST, request.FILES)
        if form.is_valid():
            # save article to db
            instance = form.save(commit=False)
            instance.author = request.user
            instance.save()
            return redirect('articles:list')
    else:
        form = forms.CreateArticle()
    return render(request, 'articles/article_create.html', {'form': form})

@login_required(login_url="/accounts/login/")
def article_delete(request, title):
    articles = Article.objects.all().order_by('date')
    try:
        article = Article.objects.get(title=title)
        article.delete()
    except article.DoesNotExist:
        return redirect('articles:list')
    #except Exception as e:
        #return HttpResponse("error")
        #return redirect('/')
    return render(request, 'articles/article_list.html', {'articles': articles})

def user_detail(request, author):
    art = Article.objects.filter(author=request.user)
    print(request.user.username)
    #a = Article.objects.all().get(author=request.user)
    return render(request, 'articles/text.html', {'err': art})

djangonautic/views.py
from django.http import HttpResponse
from django.shortcuts import render

def homepage(request):
    # return HttpResponse('homepage')
    return render(request, 'homepage.html')

def about(request):
    # return HttpResponse('about')
    return render(request, 'about.html')

accounts/templates/accounts/login.html
{% extends 'base_layout.html' %}

{% block content %}
    <h1>Log in</h1>
    <form class="site-form" action="{% url 'accounts:login' %}" method="post">
        {% csrf_token %}
        {{ form }}
        {% if request.GET.next %}
            <input type="hidden" name="next" value="{{ request.GET.next }}" />
        {% endif %}
        <input type="submit" value="Login" />
    </form>
    <p>Not got an account? <a href="{% url 'accounts:signup' %}">Sign Up</a></p>
{% endblock %}

accounts/templates/accounts/profile.html
{% extends 'base_layout.html' %}

{% block content %}
<h3>Written by {{ request.user }}</h3>
<p>{{ form }}</p>
{% endblock %}

accounts/templates/accounts/signup.html
{% extends 'base_layout.html' %}

{% block content %}
    <h1>Signup</h1>
    <form class="site-form" action="{% url 'accounts:signup' %}" method="post">
        {% csrf_token %}
        {{ form }}
        {{ details }}
        <input type="submit" value="Signup">
    </form>
{% endblock %}

articles/templates/articles/article_create.html
{% extends 'base_layout.html' %}

{% block content %}
<script src="https://cloud.tinymce.com/stable/tinymce.min.js"></script>
  <script>tinymce.init({ selector:'textarea' });</script>

  <!--<textarea>Next, get a free Tiny Cloud API key!</textarea>-->
    <div class="create-article">
        <h2>Create an Awesome New Article</h2>
        <form class="site-form" action="{% url 'articles:create' %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form }}
            <input type="submit" value="Create">
        </form>
    </div>

  


    <script src="/static/slugify.js"></script>
{% endblock %}

articles/templates/articles/article_detail.html
{% extends 'base_layout.html' %}

{% block content %}
<div class="article-detail">
    <div class="article">
        <img src="{{ article.thumb.url }}" />
        <h2>{{ article.title }}</h2>
        <!--<h3>Written by {{ article.author.username }}</h3>-->
        <h3>Written by <a href="localhost:8000/accounts/profile/">{{ article.author.username }} </a></h3>
        
        <p>{{ article.body }}</p>
        <p>{{ article.date }}</p>
    </div>
</div>
{% endblock %}

articles/templates/articles/article_list.html
{% extends 'base_layout.html' %}

{% block content%}
    <h1>Articles List</h1>
    <div class="articles">
    {% for article in articles %}
        <div class="article">
            <h2><a href="{% url 'articles:detail' slug=article.slug %}">{{ article.title }}</a></h2>
            <p>{{ article.snippet }}</p>
            <p>{{ article.date }}</p>
            <a class="author" href="#" >added by {{ article.author.username }}</a>
        </div>
    {% endfor %}
    </div>
{% endblock %}

articles/templates/articles/text.html
{{ err }}

templates/about.html
{% extends 'base_layout.html' %}

{% block content %}
<div class="wrapper">
    <h1>About Us</h1>
    <h3>Why django ?</h3>
    <p>With Django, you can take Web applications from concept 
    to launch in a matter of hours. Django takes care of much of the hassle
     of Web development, so you can focus on writing your app without needing to 
     reinvent the wheel. It’s free and open source.</p>
     <h3><br><br></h3>
     <p>Djangonautic is a open place for anyone to write his idea, imagination, thoughts
      across the world in a very effective way .</p>
      <h3>Our Goal</h3>
      <p>Our goal is to provide a open source plateform where the peoples to share their
       ideas across the wrold. It help the peoples globaly.</p>
</div>
{% endblock %}

templates/base_layout.html
{% load static %}

<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>Djangonauts</title>
        <link rel="stylesheet" href="{% static 'styles.css' %}">
    </head>
    <body>
        <header class="wrapper">
            <h1><a href="{% url 'home' %}"><img src="{% static 'logo.png' %}" alt="djangonautic" /></a></h1>
            <nav>
                <ul>
                    {% if user.is_authenticated %}
                    <li>
                        <form class="logout-link" action="{% url 'accounts:logout' %}" method="post">
                            {% csrf_token %}
                            <li><a href="/about">About</a></li>
                            <button type="submit">Logout</button>
                        </form>
                    </li>
                    <li><a href="{% url 'articles:create' %}" class="highlight">New Article</a></li>
                    {% else %}
                    <li><a href="{% url 'accounts:login' %}">Login</a></li>
                    <li><a href="{% url 'accounts:signup' %}">Signup</a></li>
                    <li><a href="/about">About</a></li>
                    <li><a href="/admin">Admin</a></li>
                    {% endif %}
                </ul>
            </nav>
        </header>
        <div class="wrapper">
            {% block content %}
            {% endblock %}
        </div>
	<footer>
		<div class="foot">
        <h1>Copyrights</h1>
        </div>
	</footer>
    </body>
</html>